### ISSUE TITLE
Does not work on Ubuntu

### ISSUE THREAD

**Issue by mabushey** [kubernetes-sigs/krew#667] opened 2020-11-24 00:43 UTC
```
✗  kubectl krew 
krew is the kubectl plugin manager.
You can invoke krew through kubectl: "kubectl krew [command]..."

Usage:
  krew [command]

Available Commands:
  help        Help about any command
  info        Show information about a kubectl plugin
  install     Install kubectl plugins
  list        List installed kubectl plugins
  search      Discover kubectl plugins
  uninstall   Uninstall plugins
  update      Update the local copy of the plugin index
  upgrade     Upgrade installed plugins to newer versions
  version     Show krew version and diagnostics

Flags:
  -h, --help      help for krew
  -v, --v Level   number for the log level verbosity

Use "krew [command] --help" for more information about a command.
```
```
✗  kubectl krew list
F1124 00:40:21.143686   68008 root.go:58] krew local plugin index is not initialized (run "kubectl krew update")
✗  kubectl krew update
F1124 00:40:28.613795   68030 root.go:58] failed to update the local index: command execution failure, output="fatal: destination path '/home/ubuntu/.krew/index' already exists and is not an empty directory.\n": exit status 128
```

**Comment by mabushey** [comment] 2020-11-24 00:44
I fixed it with `rm -rf /home/ubuntu/.krew/index`

**Comment by corneliusweig** [comment] 2020-11-24 19:05
Interesting. Can you reproduce this?
Aside: how did you install `krew`?

**Comment by ahmetb** [comment] 2020-11-24 19:38
I’m suspecting of an old installation or corrupted index (due to possibly exiting in the middle of it)?

**Comment by corneliusweig** [comment] 2020-11-29 20:12
Please let us know if you can reproduce. Until then, let's close this issue.

/label triage/not-reproducible
/close

**Closed** 2020-11-29 20:12 UTC
