### ISSUE TITLE
how to krew work in hypekube kubectl

### ISSUE THREAD

**Issue by wu0407** [kubernetes-sigs/krew#459] opened 2020-01-06 02:30 UTC
use alias kubectl, show krew is installed,but run `kubectl krew install` failed.
```
alias kubectl='/data/k8s/bin/hyperkube kubectl'

 kubectl plugin list
The following compatible plugins are available:

/root/.krew/bin/kubectl-krew

```
use kubectl krew search show help info
```
kubectl krew search

Usage:
  hyperkube kubectl [flags] [options]

Use "hyperkube kubectl <command> --help" for more information about a given command.
Use "hyperkube kubectl options" for a list of global command-line options (applies to all commands).
```

**Comment by ahmetb** [comment] 2020-01-06 03:12
I don’t understand the issue here or what hyperkube is, but I also don’t think that has something to do with us. 

I will close this. If you think I am mistaken please explain more clearly what the issue is and why it matters. 
/close

**Closed by ahmetb** 2020-01-06 03:12 UTC

**Comment by wu0407** [comment] 2020-01-06 06:16
The hyperkube binary is an all in one binary (in a way similar to busybox), combining all the previously separate binaries.

**Comment by ahmetb** [comment] 2020-01-06 06:19
Does any other plugin work this way (through hyperkube)? Or is it just krew?

**Comment by wu0407** [comment] 2020-01-06 06:23
hyperkube containt that component 
```
Available Commands:
  cloud-controller-manager 
  help                     Help about any command
  kube-apiserver           
  kube-controller-manager  
  kube-proxy               
  kube-scheduler           
  kubectl                  kubectl controls the Kubernetes cluster manager
  kubelet
```
I not try other plugin , but find it exec kubectl-kubectl-krew，so do this link krew to kubectl-kubectl-krew  it is work.
```
ln -sv /root/.krew/store/krew/v0.3.3/krew  .krew/bin/kubectl-kubectl-krew
```

**Comment by wu0407** [comment] 2020-01-06 06:27
https://stackoverflow.com/questions/33953254/what-is-hyperkube

**Comment by ahmetb** [comment] 2020-01-07 02:09
@wu0407 sorry I don't understand what you mean here due to English problems. maybe someone can understand you.

I want you to run some other plugin (NOT krew) on hyperkube kubectl, and see if it works. I suspect it doesn't. Then you should open the issue to their repo, not krew.

If krew is the only plugin that doesn't work, we will reopen this. But I need clear communication from you. Maybe explain your problem to someone else who help you explain better here.

**Comment by corneliusweig** [comment] 2020-01-09 22:03
Just speculating: are you using an old version of `hyperkube`? The plugin system has been completely reworked in version 1.12.

Anyway, hyperkube seems to work differently today (I can only find a hyperkube docker image), and it looks like it is going to be deprecated (see https://kubernetes.io/docs/setup/release/notes/). I'd suggest to switch to standard tooling instead ;)
